### ISSUE TITLE
CarouselLayoutManager constructor error after upgrading to 2.0.1

### ISSUE THREAD

**Issue by jasonMisaq** [leochuan/ViewPagerLayoutManager#23]
I just upgraded to 2.0.1 and now in all CarouselLayoutManager constructors I get the following error when trying to run the app:   

```
    protected CarouselLayoutManager createLayoutManager() {
        return new CarouselLayoutManager(Util.Dp2px(this, 100));
    }
Error:(80, 52) error: incompatible types: int cannot be converted to Builder
```  
Has the constructor signature changed in the new version?

**Comment by leochuan** [comment]
@jasonMisaq I changed `ViewPagerLayoutManager` to implement LinearLayoutManager, So you have to pass a `Context` into constructor now.
